name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install tdlib
      run: |
        git clone --depth 1 --recursive https://github.com/tdlib/td.git
        mkdir -p td/build
        cd td/build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -- -j5
        make install
        cd -

    - name: Build
      run: |
        cd addchatuser
        go build -v .

